import Head from "next/head";
import { useState } from "react";
export default function Home() {

  const [response, setResponse] = useState("")
  const [message, setMessage] = useState("")
  const [pending,setPending] = useState(null)

  const handleChange = (e) => {
    setMessage(e.target.value)
  }
  
  const handleClick = async () => {
    setPending(true)
     try {
      let response = await fetch("/api/gpt",{
        method:"POST",
        headers:{
          "Content-Type": "applications/json"
        },
        body:JSON.stringify(message)
      })
      let data = await response.json()
      setResponse(data)
      setPending(false)
      setMessage("")

    } catch (error) {
      console.log(error.messsage)
    }


  }
  return (
    <div className="flex flex-col min-h-screen bg-slate-100">
      <Head>
        <title>Ai Twitter Message App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="flex-1 flex items-center justify-center">
        <div className="max-w-screen-lg mx-auto text-center text-4xl pb-24">
          {pending && <p>Ai is generating response</p>}
          {response}
        </div>
      </div>

      <div className="fixed bottom-0 bg-slate-300 p-4 w-full">
        <div className="max-w-screen-lg mx-auto flex gap-2">
          <input type="text" className="flex-1 p-4 rounded" value={message} onChange={handleChange} />
          <button className="py-4 px-6 bg-slate-700 text-white rounded" onClick={handleClick}>
            Submit
          </button>
        </div>
      </div>
    </div>
  );
}
